### ISSUE TITLE
Can you support the following nightcout  url format: http://x.x.x.x:1234

### ISSUE THREAD

**Issue by jizhongwen** [PedanticAvenger/FlashCGM#21]
When I use the following nightcout  url format: http://x.x.x.x:1234, the FlashCGM does not work. When I use the spike format in your wiki, it works. Thanks for sharing this good watch face to us.

**Comment by PedanticAvenger** [comment]
I think I need more details regarding what you are looking for.
Do you mean http:// vs https:// ?

**Comment by jizhongwen** [comment]
The wiki is https://{yournightscoutFQDN}/ ,But my site is http with 4 number port. Thanks for your answer

**Comment by PedanticAvenger** [comment]
There are challenges on some phone platforms with trying to connect off the phone with http://  there are cases where https:// is the only thing supported.  This is supposed to be addressed in future fitbit updates but apparently can be impacted by OS variants on the Android side.  If you need it to work today my best suggestion is to secure the website, perhaps with something like a letencrypt certificate.

**Comment by jizhongwen** [comment]
thanks.

**Comment by PedanticAvenger** [comment]
Limitation on the phone OS security side and not currently something that I can work around.
