### ISSUE TITLE
Updates Stop

### ISSUE THREAD

**Issue by justingshreve** [PedanticAvenger/FlashCGM#22]
I love the watchface and works great, however it sporadically stops working. BGs stop showing on the watch. Says 'unset' and time since last reading was received. I'm using xdrip plus and that is showing most recent BG. I've tried restarting watch (versa) and updating the URLs, but doesn't seem to come back easily and I'm currently stuck. Any ideas on how to restart the process to get BGs flowing again? Is there a setting in xdrip+ I might be able to adjust? Thanks for great work!

**Comment by PedanticAvenger** [comment]
Waiting on firmware updates for watches to improve connection stability.  Highly variable timeframes between different phone manufacturers as well.
