### ISSUE TITLE
Data not transferring to Versa

### ISSUE THREAD

**Issue by jennyugalde** [PedanticAvenger/FlashCGM#23]
I have a miaomiao to transfer Freestyle Libre data to my Android phone. I have just set up the Versa to get the bg readings there. Just the grey X where the bg should be.
I have a Nightscout account set up and also xdrip+, everything working fine with that. But the clock doesn't pick up the bg even though I have pointed the Settings API URL and the Data API URL to my working Nightscout account. Any advice?

**Comment by john36m** [comment]
I have poor connectivity with a iPhone 6plus under iOS 11.4 using Spike.  It will get readings for a short period of time and then stop.  I have poor connectivity on all Fitbit Versa CGM watchfaces.

**Comment by PedanticAvenger** [comment]
@jennyugalde Can you open the settings and data API urls on your phones browser directly and are you getting data back?

@john36m Sounds like connectivity stability between the watch and the phone.  The best place to follow up on those kinds of issues is the fitbit forums, the most recent set of firmware updates have all been focused heavily on improving this stability but I have to restart my versa and phone occasionally to get things going again.

**Comment by PedanticAvenger** [comment]
Closing pending updates/responses to the testing suggestions.
