### ISSUE TITLE
fitbit ionic not receiving bg data from xdrip+ 

### ISSUE THREAD

**Issue by seanponeill** [PedanticAvenger/FlashCGM#24]
I haven't been able to successfully get a reading from my xdrip+ on my Fitbit Ionic. Still "unset" with grey "x." What am i doing wrong?

**Comment by PedanticAvenger** [comment]
1) Can you confirm the URLs you have in the settings for settings and data?
2) Can you connect to these same URLs via a browser on your phone to confirm that the pages are being provided correctly?

**Comment by carols100** [comment]
I’m having similar problems with Sime not transferring bg to ionic

**Comment by brlidman** [comment]
I'm having the same issue. In the wiki it states for XDrip+ to not include any URLs in the settings, is that not the case anymore?

BTW thank you for making an awesome watchface :)

**Comment by PedanticAvenger** [comment]
That URL is the "default" if you put nothing into the settings.
The first thing that needs to be done is open chrome or whatever browser on your phone (the same phone running xdrip) and try to open both http://127.0.0.1:17580/sgv.json and http://127.0.0.1:17580/status.json  I'm not certain that xdrip starts the web server by default yet so this is to make sure you have it enabled and that xdrip is prociding the data.

**Comment by PedanticAvenger** [comment]
If you get results back (text data, formatted with a bunch of {} and commas) then there is certainly no problem with putting those URLs specifically into the watchface configuration fields.  I haven't tested the defaults for a bit as I point to different data sources constantly to help people test things with nightscout.

**Comment by brlidman** [comment]
Thank you for the response!

I'm seeing results for both of those sites (I can add screenshots if helpful), but pointing to both still wasn't working. I then tried to go back to pointing both to my Nightscout site and for some reason that didn't work either (it said mg/dl instead of UNSET but still gray X).

I then did it as you suggested in the wiki now with the settings pointing to Nightscout and data blank (using XDrip) and that works! I think I'll just keep this set up that I know works :).

Thank you again for all your help!

**Comment by PedanticAvenger** [comment]
Screenshots of what you get from those URLs would be helpful.  I do fairly specific checks for what gets returned for units and have already been bitten by looking for mmol/L and some giving mmol/l for reasons I couldn't figure out.  If there is a different way of presenting units I would love to see them all and make a more generic/safer check.

**Comment by brlidman** [comment]
Here are the screenshots, let me know if there's anything else I can help with.

![image](https://user-images.githubusercontent.com/40373954/42712561-faf08cd0-86a0-11e8-8d13-ba1922aaf614.png)
![image](https://user-images.githubusercontent.com/40373954/42712576-0ab943c8-86a1-11e8-8d32-e8c994059989.png)

**Comment by PedanticAvenger** [comment]
And exactly the same problem again.  For some reason your xdrip is displaying "mg\/dl" rather than "mg/dl"

**Comment by PedanticAvenger** [comment]
Ok, hopefully the build I'm about to release to the mainstream should cover all the situations like this one could encounter now.  Please let me know after it updates if there are further issues.
