### ISSUE TITLE
Watch face not working 

### ISSUE THREAD

**Issue by christians21** [PedanticAvenger/FlashCGM#26]
I have followed the instructions to have this watch face on fitbit versa. However, the BG readings have a grey X and above says unset? I have copied exactly what the settings URL and Data URL should be with my nightscoutFQDN but it still does not work. Any ideas?

**Comment by PedanticAvenger** [comment]
Have you tried opening the full URL you specified in the config on the phones web browser to confirm reachability?  That would be my first troubleshooting step.  Next would be to check if you have read-only access setup as a default for your site.

**Comment by PedanticAvenger** [comment]
Did you have any luck getting a connection?

**Comment by PedanticAvenger** [comment]
No updates
