### ISSUE TITLE
Versa not able to connect

### ISSUE THREAD

**Issue by mblaylock67** [PedanticAvenger/FlashCGM#27]
Can someone please give me directions on how to set this up to read my nightscout? I tried to find this online but I was not able to find and step by step directions. I have a nightscout account and I have down loaded the watchface. What do I do from here?

**Comment by PedanticAvenger** [comment]
Hi, if you look in the wiki here (https://github.com/PedanticAvenger/FlashCGM/wiki) and scroll down to the "Setting up" section it should show you what you need to do.  You should have the URL to your nightscout site on hand and with that the section shows you how to setup your two URLs.

**Comment by mblaylock67** [comment]
Ok I though I did this right but all I get is an "X". 

This is an example of the URL 

https://APPNAME.herokuapp.com/api/v1/status.js

What am I still doing wrong?

**Comment by PedanticAvenger** [comment]
No updates.  Assuming closed.
