### ISSUE TITLE
Fitbit ionic not displaying graph

### ISSUE THREAD

**Issue by timmy354321** [PedanticAvenger/FlashCGM#29]
Im using xdrip with the settings api as http://127.0.0.1:1758/status.json
the data api as http://127.0.0.1:17580/sgv.json and i'm able to see the numerical data and the arrow on the watch face however the graph is not working properly. new data points change the scale values and the chart remains flat. 
![IMG_20190327_1607166](https://user-images.githubusercontent.com/48967293/55112414-8bb3f580-50aa-11e9-9a0e-913bd1a392a8.jpg)
![IMG_20190327_1607075](https://user-images.githubusercontent.com/48967293/55112415-8bb3f580-50aa-11e9-814e-1b526e7229ef.jpg)

**Comment by PedanticAvenger** [comment]
It's seems to be working properly for the data URL you entered. What seems
to be missing is the ?count=24 and right now it's graphing only one point.

You can refer to the wiki for config guidance.
https://github.com/PedanticAvenger/FlashCGM/wiki

**Comment by PedanticAvenger** [comment]
About a month since last update.
Assuming resolved.
