### ISSUE TITLE
I get data but graph is a flat line and I don't recieve low alerts.

### ISSUE THREAD

**Issue by herfst** [PedanticAvenger/FlashCGM#40]
I succesfully installed your whatchface but the graph shows always a flat line and I get alerts for high but not for low.

**Comment by PedanticAvenger** [comment]
Are you able to upload a couple pics showing exactly what is displayed?
For the alerts please check to be sure that there are no typos in the entry for value for low alerts like a space or something like that.

**Comment by herfst** [comment]
Hello,

I used a comma, and changed it to a dot. Is that correct?

Here by a screenshot of the graph.

I hope you can help me.

Mariska


Op di 20 okt. 2020 20:24 schreef Raymond Richmond <notifications@github.com

**Comment by herfst** [comment]
Op di 20 okt. 2020 20:24 schreef Raymond Richmond <notifications@github.com

**Comment by PedanticAvenger** [comment]
I didn't code much regarding internationalization so the comma instead of the period is likely the source of the problem for the low alerts.  Might also be the source of the issues with the graph issue as well.  After changing that, restart your watch and see if the graph resets.

**Comment by herfst** [comment]
thank you very much, it works now!

Op di 20 okt. 2020 om 20:59 schreef Raymond Richmond <
notifications@github.com>:

**Comment by herfst** [comment]
another question, I can snooze 30 minutes or 4 ours, but I would like to
snooze also 1 or 2 ours. Is that possible?

Op di 20 okt. 2020 om 21:20 schreef Mariska Aalbers <
mariska.aalbers91@gmail.com>:
