### ISSUE TITLE
Versa 3 Support

### ISSUE THREAD

**Issue by Cagier** [PedanticAvenger/FlashCGM#42]
This is the BEST CGM watchface for Fitbit but it is not yet compatible with the Versa 3.  It would be fantastic to see this implemented soon.

**Comment by PedanticAvenger** [comment]
Your desire has been heard and has not fallen on deaf ears.  I am working on this but it is taking longer than I had hoped due to the newer code versions on the new devices not including some of the nice simple features I had used previously requiring me to rewrite them and back-port them to all the other models too to keep this supportable.  It is coming tho. :)

**Comment by Cagier** [comment]
That's fantastic news Raymond. Great support for Versa 2 previously and now Versa 3 . Looking forward to the next release. Thank you so much.

**Comment by PedanticAvenger** [comment]
There is a link in the wiki to the dev build for the watch face.  I've added a build for the Versa 3 and sense there.  I'm still working on this and will be tweaking things but I have all the current functionality and some new feature built in.  If you want to give it a try.  I still only have the simulator so will need some feedback on how it works.

**Comment by PedanticAvenger** [comment]
Look for the Dev and Bugfix branch link off to the side.  Once it is stable and I roll the enhancements down to the Ionic/Versa branch as well I will roll it out to the production Gallery.

**Comment by PedanticAvenger** [comment]
The big thing you need to be aware of is the new "Configurable Snooze timers" for the alerts.  They need to be configured in the fitbit app before the watchface will work, I haven't coded in defaults yet so you have to set them up on the phone then restart your watchface after installing.  That should be addressed shortly.

**Comment by Cagier** [comment]
Thanks Raymond.  That's all sounds really good. We will take a look at it
tonight.
Cheers

**Comment by Cagier** [comment]
We have set up the watchable successfully and after a couple of restarts we
are getting readings. Will do a "soak test" over the coming days and report
back any issues that we encounter. However, initial impressions are that
everything works and fields fit well on the watchface. Looks great so well
done again!

**Comment by PedanticAvenger** [comment]
No news is....

**Comment by Cagier** [comment]
Yes, functionally speaking, it has been working very well. Thanks so much again!

There are serious problems syncing though but this seems to be a problem with a variety of watchfaces so I was not putting it down specifically to this app and more down to Fitbit.  (blood sugar is on the watch and watch is synching health data but watchfaces says stale data.)
